name: resolve_statistics

channels:
    - defaults
    - conda-forge
    - astropy

dependencies:
    - python>=3.7
    - astropy
    - sphinx
    - pip
    - pip:
        - GitPython
        - configparser
          #- sphinx-astropy
        - sphinx_rtd_theme
          #- sphinx-automodapi  
