name: resolve_statistics

channels:
  - defaults
  - astropy

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - astropy
  - h5py
  - numpy
  - pandas
  - scipy
    # Removed halotools to install from source instead
    # - halotools
  - seaborn
  - sphinx>=1.6
  - sphinx-automodapi
  - pip
  - emcee
  - pip:
      - GitPython
      - progressbar2
      - cosmo-utils
      - configparser
      - sphinx-astropy
      - sphinx_rtd_theme
      - sphinx-automodapi
      - git+https://github.com/astropy/halotools.git
