name: resolve_statistics

channels:
  - defaults
  - astropy

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - astropy
  - h5py
  - numpy
  - pandas
  - scipy
  - halotools
  - seaborn
  - sphinx>=1.6
  - pip
  - pip:
      - GitPython
      - progressbar2
      - cosmo-utils
      - configparser
      - sphinx-astropy
      - sphinx_rtd_theme
      - sphinx-automodapi
