name: resolve_statistics

channels:
  - defaults
  - astropy
  - conda-forge

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - astropy
  - h5py
  - numpy
  - pandas
  - scipy
 # Removed halotools to install it from source instead
 #- halotools
  - seaborn
 #- sphinx>=1.6
  - pip
  - emcee=2.2.1
  - imagemagick
  - pip:    
      - GitPython
      - progressbar2
      - cosmo-utils
      - configparser
     #- sphinx-astropy
     #- sphinx_rtd_theme
     #- sphinx-automodapi
     #- astroid<2.3
     #- pylint<2.4
      - chainconsumer
      - git+https://github.com/astropy/halotools.git@master
